/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shablloni4;

import javax.swing.ButtonModel;

/**
 *
 * @author ermal_abiti
 */
public class AplikacioniPerStudimeMaster extends javax.swing.JFrame {
    
    int userID = 0;
    /**
     * Creates new form AplikacioniPerStudimeMaster
     */
    public AplikacioniPerStudimeMaster() {
        initComponents();
        labelaOutputError.setVisible(false);
        labelaOutputSuccess.setVisible(false);
        labelaPerBach.setVisible(false);
        comboPerBach.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        titulliFormes = new javax.swing.JLabel();
        fieldEmri = new javax.swing.JTextField();
        fieldMosha = new javax.swing.JTextField();
        fieldMbiemri = new javax.swing.JTextField();
        fieldKomuna = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        butoniApliko = new javax.swing.JButton();
        butoniAnulo = new javax.swing.JButton();
        fieldConfirmPw = new javax.swing.JPasswordField();
        fieldPassword = new javax.swing.JPasswordField();
        labelaOutputError = new javax.swing.JLabel();
        labelaOutputSuccess = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelaDrejtimi = new javax.swing.JLabel();
        comboDrejtimi = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        comboPerBach = new javax.swing.JComboBox<>();
        labelaPerBach = new javax.swing.JLabel();
        fieldNotaMesatare = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikimi Për Studime Master - University of Business and Technology");
        setResizable(false);

        titulliFormes.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        titulliFormes.setText("Aplikimi Për Studime MASTER - UBT");

        fieldEmri.setToolTipText("Minimumi: 2 Karaktere");

        jLabel1.setText("Emri:");

        jLabel2.setText("Mbiemri:");

        jLabel3.setText("Mosha:");

        jLabel4.setText("Komuna:");

        jLabel5.setText("E-mail:");

        jLabel6.setText("Confirm Password:");

        jLabel7.setText("Password:");

        butoniApliko.setText("APLIKO");
        butoniApliko.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        butoniApliko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butoniAplikoActionPerformed(evt);
            }
        });

        butoniAnulo.setText("ANULO");
        butoniAnulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)));
        butoniAnulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butoniAnuloActionPerformed(evt);
            }
        });

        labelaOutputError.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelaOutputError.setForeground(new java.awt.Color(255, 51, 51));
        labelaOutputError.setText("OutPut-i per gabime gjate aplikimit");

        labelaOutputSuccess.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelaOutputSuccess.setForeground(new java.awt.Color(51, 153, 0));
        labelaOutputSuccess.setText("OutPut-i pas aplikimit me sukses");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("TE DHENAT PERSONALE");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("TE DHENAT UNIVERSITARE");

        labelaDrejtimi.setText("Drejtimi:");

        comboDrejtimi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--zgjedh drejtimin--", "Shkenca Kompjuterike dhe Inxhinieri", "Infiermjeri", "Kontabilitet", "Banka dhe Financa", "Informatike", "Zhvillim i Aplikacioneve iOS/Android" }));

        jLabel9.setText("Studimet BACHELOR:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("UBT");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Tjeter");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        comboPerBach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- zgjedh Universitetin apo Kolegjin --", "Universiteti i Prishtines - UP", "Universiteti i Tiranes", "Kolegji AAB", "Kolegji Universum" }));

        labelaPerBach.setText("Institucioni Per BACHELOR:");

        fieldNotaMesatare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNotaMesatareActionPerformed(evt);
            }
        });

        jLabel10.setText("Nota Mesatare:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(titulliFormes)
                .addContainerGap(487, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelaOutputError, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldEmri)
                                    .addComponent(fieldKomuna, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(fieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(fieldMosha, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(fieldMbiemri, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(fieldPassword)
                                    .addComponent(fieldConfirmPw))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(labelaDrejtimi))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboDrejtimi, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(labelaPerBach))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPerBach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNotaMesatare, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(butoniAnulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butoniApliko, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelaOutputSuccess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulliFormes)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldEmri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldMbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelaOutputSuccess)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelaDrejtimi)
                                    .addComponent(comboDrejtimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldMosha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldKomuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboPerBach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelaPerBach))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNotaMesatare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldConfirmPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(labelaOutputError)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butoniAnulo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(butoniApliko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butoniAplikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butoniAplikoActionPerformed
        labelaOutputError.setVisible(false);
        labelaOutputSuccess.setVisible(false);
        
        
        if(fieldEmri.getText().length() < 2){
            labelaOutputError.setText("Fusha EMRI duhet te jete me e gjate se 2 karaktera!");
            labelaOutputError.setVisible(true);
        }
        
        else if(fieldMbiemri.getText().length() < 2){
            labelaOutputError.setText("Fusha MBIEMRI duhet te jete me e gjate se 2 karaktera!");
            labelaOutputError.setVisible(true);
        }
        
        else if(fieldMbiemri.getText().length() < 2){
            labelaOutputError.setText("Fusha MBIEMRI duhet te jete me e gjate se 2 karaktera!");
            labelaOutputError.setVisible(true);
        }
        
        else if(fieldMosha.getText().length()<=0 || (Integer.parseInt( fieldMosha.getText() ) ) < 18) {
            labelaOutputError.setText("Ju duhet te jeni te pakten ne moshen 18 vjeqare per te aplikuar!");
            labelaOutputError.setVisible(true);
        }
        
        else if(fieldKomuna.getText().length() <= 0){
            labelaOutputError.setText("Fusha KOMUNA nuk duhet te jete e zbrazet!");
            labelaOutputError.setVisible(true);
        }
        
        else if(fieldKomuna.getText().length() <= 0){
            labelaOutputError.setText("Fusha KOMUNA nuk duhet te jete e zbrazet!");
            labelaOutputError.setVisible(true);
        }
        
        else if(fieldEmail.getText().length() <= 0 || (!(fieldEmail.getText().contains("@")))){
            labelaOutputError.setText("Shkruani nje E-mail valide per te aplikuar!");
            labelaOutputError.setVisible(true);
        }
        
        else if(fieldPassword.getPassword().length < 8){
            labelaOutputError.setText("Passwordi duhet te kete se paku 8 karaktere!");
            labelaOutputError.setVisible(true);
        }
        
        else if( !(fieldConfirmPw.getText().equals(fieldPassword.getText())) ){
            labelaOutputError.setText("Passwordi i dyte duhet te perputhet me passworin e pare!");
            labelaOutputError.setVisible(true);
        }
        
        else if(comboDrejtimi.getSelectedItem().toString().equals(comboDrejtimi.getItemAt(0))){
            labelaOutputError.setText("Ju Lutem Zgjidheni Drejtimin per te aplikuar!");
            labelaOutputError.setVisible(true);
        }
        else if(comboPerBach.isVisible() && comboPerBach.getSelectedItem().toString().equals(comboPerBach.getItemAt(0))){
            labelaOutputError.setText("Ju Lutem Zgjidheni Institucionin e meparshem per te aplikuar!");
            labelaOutputError.setVisible(true);   
        }
        
        else if(fieldNotaMesatare.getText().length() < 1 || Double.parseDouble(fieldNotaMesatare.getText()) < 8.0 || Double.parseDouble(fieldNotaMesatare.getText()) > 10){
            labelaOutputError.setText("Na vjen keq por nota e juaj mesatare duhet te jete te pakten 8.0 ose me e larte per te aplikuar studimet MASTER!(shtypni note mesatare korrekte)");
            labelaOutputError.setVisible(true);
        }
        
        else {
            labelaOutputSuccess.setText("Ju keni aplikuar me sukses!");
            labelaOutputError.setVisible(false);
            labelaOutputSuccess.setVisible(true);
            userID++;
            printRegisteredUser(fieldEmri.getText(), fieldMbiemri.getText(), fieldMosha.getText(), fieldKomuna.getText(), fieldEmail.getText(), comboDrejtimi.getSelectedItem().toString(), fieldNotaMesatare.getText());
        }
        
    }//GEN-LAST:event_butoniAplikoActionPerformed

    private void butoniAnuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butoniAnuloActionPerformed
        
        labelaOutputError.setVisible(false);
        labelaOutputSuccess.setVisible(false);
        
        fieldEmri.setText("");
        fieldMbiemri.setText("");
        fieldMosha.setText("");
        fieldKomuna.setText("");
        fieldEmail.setText("");
        fieldPassword.setText("");
        fieldConfirmPw.setText("");
        fieldNotaMesatare.setText("");
        
        comboDrejtimi.setSelectedIndex(0);
        
        //Institucioni i meparshem COMBO BOX and LABEL
        comboPerBach.setSelectedIndex(0);
        jRadioButton1.setSelected(true);
        jRadioButton1ActionPerformed(evt);
    }//GEN-LAST:event_butoniAnuloActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        labelaPerBach.setVisible(false);
        comboPerBach.setVisible(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        labelaPerBach.setVisible(true);
        comboPerBach.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void fieldNotaMesatareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNotaMesatareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNotaMesatareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikacioniPerStudimeMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikacioniPerStudimeMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikacioniPerStudimeMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikacioniPerStudimeMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikacioniPerStudimeMaster().setVisible(true);
            }
        });
    }
    
    public void printRegisteredUser(String emri, String mbiemri, String mosha, String komuna, String email, String drejtimi, String notaMesatare){
        System.out.println("--------------------");
        System.out.println("USER_ID:" + this.userID);
        System.out.println("--------------------");
        System.out.println("Emri: " + emri);
        System.out.println("Mbiemri: " + mbiemri);
        System.out.println("Mosha: " + mosha);
        System.out.println("Komuna: " + komuna);
        System.out.println("E-mail: " + email);
        System.out.println("Drejtimi: " + drejtimi);
        System.out.println("Nota Mesatare: " + notaMesatare);
        System.out.println("___________________________________");
        System.out.println();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butoniAnulo;
    private javax.swing.JButton butoniApliko;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JComboBox<String> comboDrejtimi;
    private javax.swing.JComboBox<String> comboPerBach;
    private javax.swing.JPasswordField fieldConfirmPw;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEmri;
    private javax.swing.JTextField fieldKomuna;
    private javax.swing.JTextField fieldMbiemri;
    private javax.swing.JTextField fieldMosha;
    private javax.swing.JTextField fieldNotaMesatare;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel labelaDrejtimi;
    private javax.swing.JLabel labelaOutputError;
    private javax.swing.JLabel labelaOutputSuccess;
    private javax.swing.JLabel labelaPerBach;
    private javax.swing.JLabel titulliFormes;
    // End of variables declaration//GEN-END:variables
}
